### ISSUE TITLE
Editing pass on Toolbox

### ISSUE THREAD

**Issue by leafac** [jhu-oose/www.jhu-oose.com#1]
Please, @ykl7

**Comment by ykl7** [comment]
On it

**Comment by leafac** [comment]
See if you like the logo better now. I can give you more versions if you don’t like this one.

**Comment by ykl7** [comment]
Logo looks cleaner and decipherable. It's good!

**Comment by ykl7** [comment]
Typos:
- Duh, not D'uh (Chrome)

'Inform to Git your name and email' does not make sense to me. (Git)

I will find more possible edits and make changes for all of them after doing a whole read-through and send a PR.

**Comment by leafac** [comment]
I’ll wait for your PR, then.
