### ISSUE TITLE
Travis test failure if todoose is offline

### ISSUE THREAD

**Issue by ykl7** [jhu-oose/www.jhu-oose.com#5]
In case the Heroku instance of todoose shuts down, the tests fail. This can happen due to inactivity for 30 minutes. So, when creating a PR, for tests to pass, the app has to be 'activated' first

**Comment by leafac** [comment]
Usually Heroku apps wake up really fast, but TODOOSE seems to take a long time, probably because it’s in Java. How about we just [ignore](https://github.com/gjtorikian/html-proofer#ignoring-content) that link?

**Comment by ykl7** [comment]
Yeah, that seems like a good idea
